name: Build & Deploy to AWS ECS

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ECS_SERVICE: ${{ secrets.ECS_SERVICE }}
      ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Debug environment variables
        run: |
          echo "AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID}"
          echo "AWS_REGION=${AWS_REGION}"
          echo "ECR_REPOSITORY=${ECR_REPOSITORY}"

      - name: Check target directory
        run: |
          ls -la target/
          if [ ! -f target/*.jar ]; then
            echo "No JAR file found in target/"
            exit 1
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Docker image
        run: |
          # Дебаг: виведемо всі змінні оточення для перевірки
          echo "DEBUG: AWS_ACCOUNT_ID='$AWS_ACCOUNT_ID'"
          echo "DEBUG: AWS_REGION='$AWS_REGION'"
          echo "DEBUG: ECR_REPOSITORY='$ECR_REPOSITORY'"

          # Перевірка кожної змінної окремо
          if [ -z "$AWS_ACCOUNT_ID" ]; then
            echo "ERROR: AWS_ACCOUNT_ID is empty"
            exit 1
          fi
          if [ -z "$AWS_REGION" ]; then
            echo "ERROR: AWS_REGION is empty"
            exit 1
          fi
          if [ -z "$ECR_REPOSITORY" ]; then
            echo "ERROR: ECR_REPOSITORY is empty"
            exit 1
          fi

      - name: Update ECS service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: football-manager-task-definition-2
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
          force-new-deployment: true